### ISSUE TITLE
App context menus are shown with up/down arrows, even though they would fit on the screen

### ISSUE THREAD

**Issue by vicat28** [linuxmint/xfce4-xapp-status-plugin#2]
Hi,
I've just upgraded from Linux Mint Xfce 19.2 to 19.3 and noticed something a bit annoying.
When I click on the app's icon in the XApp Status Applet, its context menu is smaller than it should and up/down scrolling arrows are shown, even though there is a lot of free space on my screen.

This is how it looks like in the Network Manager and Telegram.

Network Manager:
![xapp_status_1](https://user-images.githubusercontent.com/30496057/71106924-6fb82d00-21c0-11ea-8a1c-4997b1d6de36.png)

Telegram:
![xapp_status_2](https://user-images.githubusercontent.com/30496057/71106971-852d5700-21c0-11ea-9eed-52b93cc4e1ef.png)

After scrolling to the top, the arrows disappear and the menu size is correct.
It is not anything I cannot live with, but it is pretty annoying as I have to hover the up arrow first to be able to select the last option.

It only happens when the panel is on top of the screen.

**Comment by m4u9** [comment]
I confirm this with top panel only.

**Comment by mtwebster** [comment]
As a temporary workaround it seems that this doesn't happen on a panel height of 32 or less (at least for me).  I haven't been able to nail down the reason for this yet.

**Comment by clefebvre** [comment]
This is an issue in Gtk if the content of a Gtk.Menu changes after it is shown.

**Comment by Septicity** [comment]
For anyone else having issues with this, one thing that worked for me was checking `gtk.css` in my theme for any instance of `transition`, then removing any instance that affected `decoration`.
```
/* decoration {
  transition: 200ms ease-out; }
  decoration:backdrop {
    transition: 200ms ease-out; } */
```
This is the line that I /* commented out */.
I assume the menu changing its size counts as the contents changing, so it makes sense that it spurs the arrows to appear.
