### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by jamaggs** [linuxmint/xfce4-xapp-status-plugin#8]
Hello

Using Mint 22 Xfce on several systems I have a slight problem. The xapp status plugin seems to use lots of CPU - around 25%. This is not always the case - on first login it seems fine and then if I log out and in again or suspend and resume the high CPU usage starts, and also I don't seem to see the gnome network applet any more.

The precise line in my task manager with the high CPU usage is:

/usr/lib/x86_64-linux-gnu/xfce4/panel/wrapper-2.0 /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libxapp-status-plugin.so 10 25165835 xapp-status-plugin XApp Status Plugin Area where XApp Status icons appear

It's not a massive problem as just uninstalling the plugin solves the issue and the applets seem to still appear. But it took a while to realise why my fan was always spinning and my computer was more sluggish than usual.

I'm unsure if this was also an issue in Mint 21.3.

Many thanks!

James

**Comment by mndill** [comment]
I can confirm that this happens to me as well. It works well during the first login after booting, but after you log out and then back in the cpu usage goes way up (in my case, 90-100%) and the network manager icon disappears from the status tray. 

Update: What appears to happen is that the first process of libxapp-status-plugin fails to terminate when the user logs out. When the user subsequently logs in, a second process is created and the first hogs the cpu. Killing the first process fixes things, but the situation recurs with each logout/login cycle.

**Comment by billiardmarker** [comment]
Just for completeness, some information from the high cpu usage thread in the Desktops&Window Managers .. Xcfe forum ( [https://forums.linuxmint.com/viewtopic.php?t=424803] )
Xapp Status Plugin consistently goes into a loop using 100% of a cpu core when either the user logs out or the Panel Preferences tool is used to remove the plugin from the panel. The looping process can be removed with a kill -TERM but otherwise will survive the 'owning' user logging out.
The removing-from-panel behaviour can be observed in the LM22 Xfce live-install environment.
bm

**Comment by Asvera** [comment]
The nm applet keep crashing and the program xapp status plugin keeps using my cpu resources at 100% this come my notice recently and wanted to report.

Process consuing resource: 
/usr/lib/x86_64-linux-gnu/xfce4/panel/wrapper-2.0 /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libxapp-status-plugin.so 10 25165835 xapp-status-plugin XApp Status Plugin Area where XApp Status icons appear


Note: It has come to my notice that the above process was by the other user login/logout in my laptop. But on the contrary i had been facing the same problem when i am using the same user.
I am not sure whether it is related to  bug in XApp status plugin or login/Logout thing.

I have removed Xapp-status-plugin from the xfce-panel  but the network device still appear after the reboot with status-tray-plugin. If any explaination would be highly appreciated.

PS: Occurring in upgrade to LM22

**Comment by vazhnov** [comment]
Sorry I didn't see the new release 0.3.9 was made 4 days ago with the fix https://github.com/linuxmint/xfce4-xapp-status-plugin/commit/b1c57c09eeb8736d7d376cabf630500f15f594e4, and I still have 0.3.6 version in my system.

The same issue here:

Process spends 100% CPU after logout (I've connected with SSH into the laptop):
```console
 % sudo top -c -n1 -o "%CPU"

top - 14:40:27 up 51 min,  4 users,  load average: 1,00, 1,00, 0,86
Tasks: 254 total,   2 running, 252 sleeping,   0 stopped,   0 zombie
%Cpu(s): 13,6 us,  1,1 sy,  0,0 ni, 85,2 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st 
MiB Mem :   7275,1 total,   4565,2 free,   1294,4 used,   1788,6 buff/cache
MiB Swap:   2048,0 total,   2048,0 free,      0,0 used.   5980,7 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   1838 myuser    20   0  539132  41784  32640 R 100,0   0,6  17:20.63 /usr/lib/x86_64-linux-gnu/xfce4/panel/wrapper-2.0 /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libxapp-status-plugin.so + 
      1 root      20   0   22720  13284   9316 S   0,0   0,2   0:01.57 /sbin/init splash
      2 root      20   0       0      0      0 S   0,0   0,0   0:00.00 [kthreadd]
      3 root      20   0       0      0      0 S   0,0   0,0   0:00.00 [pool_workqueue_release]
…
```

I've attached with `strace`:
```console
 % sudo strace -fy -p1838
strace: Process 1838 attached with 6 threads
[pid  2173] futex(0x63f8d2440240, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid  1937] restart_syscall(<... resuming interrupted read ...> <unfinished ...>
[pid  1855] restart_syscall(<... resuming interrupted read ...> <unfinished ...>
[pid  1854] restart_syscall(<... resuming interrupted read ...> <unfinished ...>
[pid  1853] futex(0x63f8d211fcb0, FUTEX_WAIT_PRIVATE, 1, NULL
```

and nothing changes in the output.

Some system info:
```console
 % cat /etc/os-release 
NAME="Linux Mint"
VERSION="22 (Wilma)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 22"
VERSION_ID="22"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=wilma
UBUNTU_CODENAME=noble

 % dpkg -S /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libxapp-status-plugin.so
xfce4-xapp-status-plugin: /usr/lib/x86_64-linux-gnu/xfce4/panel/plugins/libxapp-status-plugin.so

 % apt-cache policy xfce4-xapp-status-plugin
xfce4-xapp-status-plugin:
  Installed: 0.3.6+wilma
  Candidate: 0.3.6+wilma
  Version table:
 *** 0.3.6+wilma 500
        500 https://ftp.icm.edu.pl/pub/Linux/dist/linuxmint/packages wilma/backport amd64 Packages
        100 /var/lib/dpkg/status

 % neofetch
             ...-:::::-...                 myuser@my-HP-Laptop-15s-eq2 
          .-MMMMMMMMMMMMMMM-.              -------------------------------- 
      .-MMMM`..-:::::::-..`MMMM-.          OS: Linux Mint 22 x86_64 
    .:MMMM.:MMMMMMMMMMMMMMM:.MMMM:.        Host: HP Laptop 15s-eq2xxx 
   -MMM-M---MMMMMMMMMMMMMMMMMMM.MMM-       Kernel: 6.8.0-50-generic 
 `:MMM:MM`  :MMMM:....::-...-MMMM:MMM:`    Uptime: 1 hour 
 :MMM:MMM`  :MM:`  ``    ``  `:MMM:MMM:    Packages: 2048 (dpkg) 
.MMM.MMMM`  :MM.  -MM.  .MM-  `MMMM.MMM.   Shell: zsh 5.9 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   Resolution: 1920x1080 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM:MMM:   Terminal: /dev/pts/0 
:MMM:MMMM`  :MM.  -MM-  .MM:  `MMMM-MMM:   CPU: AMD Ryzen 3 5300U with Radeon Graphics (8) @ 3.900GHz 
.MMM.MMMM`  :MM:--:MM:--:MM:  `MMMM.MMM.   GPU: AMD ATI 03:00.0 Lucienne 
 :MMM:MMM-  `-MMMMMMMMMMMM-`  -MMM-MMM:    Memory: 1047MiB / 7275MiB 
  :MMM:MMM:`                `:MMM:MMM:
   .MMM.MMMM:--------------:MMMM.MMM.                              
     '-MMMM.-MMMMMMMMMMMMMMM-.MMMM-'                               
       '.-MMMM``--:::::--``MMMM-.'
            '-MMMMMMMMMMMMM-'
               ``-:::::-``
```
